// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using iconicJson;
//
//    var iconicData = IconicData.FromJson(jsonString);

namespace iconicJson {
    [System.Serializable]
    public class iconicData {
        public Module[] modules;
    }

    [System.Serializable]
    public class Module {
        public string key;
        public string raw;
        public string[] parts;
    }
}
